apiVersion: v1
kind: Pod 
metadata:
  name: ci-pod
  labels:
    app: ci-app
  namespace: practice-ns
spec: 
  containers: 
  - name: nginx-ci-container
    image: nginx:latest
    ports: 
    - name: nginx-port
      containerPort: 80