apiVersion: v1
kind: Pod
metadata: 
  name: ci-pod
  labels: 
    env: devops
  namespace: ns-manifest
spec: 
  containers:
  - name: nginx-ci-container
    image: nginx:latest
    ports:
    - name: ci-port
      containerPort: 80