apiVersion: v1
kind: Pod
metadata:
  name: lb-pod
  namespace: practice-ns
  labels: 
    app: lb-app
spec:
  containers:
  - name: tomcat-cont 
    image: tomcat:latest 
    ports: 
    - name: lb-port 
      containerPort: 8080