apiVersion: v1  
kind: Service
metadata:
  name: lb-svc 
  namespace: practice-ns
  labels:
    app: lb-app
spec:
  type: LoadBalancer  
  selector: 
    app: lb-app
  ports:
  - name: lb-svc-port
    protocol: TCP
    port: 80
    targetPort: 8080