apiVersion: v1 
kind: Service
metadata:
  name: np-svc
  namespace: practice-ns
  labels:
    app: np-app
spec: 
  type: NodePort
  selector:
    app: np-app
  ports:
  - name: np-svc-port
    protocol: TCP 
    port: 80
    targetPort: 80      
