apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-ingress
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ingressClassName: kong
  rules:
  - host: k8s-kong-kongkong-77cadf0124-f46b0a87dc96fe93.elb.ap-south-1.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-home-svc
            port:
              number: 80
      - path: /mobile
        pathType: Prefix
        backend:
          service:
            name: my-mobile-svc
            port:
              number: 80
      - path: /laptop
        pathType: Prefix
        backend: 
          service: 
            name: my-laptop-svc
            port: 
              number: 8080